# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171210_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
