# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-18 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171212_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('login', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskInSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Session')),
            ],
        ),
        migrations.RemoveField(
            model_name='concept',
            name='tags',
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.Tag'),
        ),
        migrations.AddField(
            model_name='taskinsession',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Task'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Student'),
        ),
        migrations.AddField(
            model_name='session',
            name='tasks',
            field=models.ManyToManyField(through='catalog.TaskInSession', to='catalog.Task'),
        ),
    ]
