# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-19 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171218_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='example',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
