# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_task_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Concept')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Task')),
            ],
        ),
    ]
