# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_taskinconcept'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='tasks2',
            field=models.ManyToManyField(blank=True, related_name='tasks2Concept', through='catalog.TaskInConcept', to='catalog.Task'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasksConcept', to='catalog.Task'),
        ),
    ]
