# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-20 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_concept_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='tasks2',
        ),
        migrations.AddField(
            model_name='concept',
            name='tasks',
            field=models.ManyToManyField(blank=True, through='catalog.TaskInConcept', to='catalog.Task'),
        ),
    ]
