# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-12-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20171220_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinsession',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
