# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180223_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
