# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-03-05 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180302_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ver',
            field=models.PositiveIntegerField(default=1),
        ),
    ]

