# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_task_ver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptInGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Concept')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Grade')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='concepts1',
            field=models.ManyToManyField(blank=True, related_name='concept1', through='catalog.ConceptInGrade', to='catalog.Concept'),
        ),
    ]
