# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180308_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='concepts',
        ),
    ]
