# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_grade_concepts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='concepts1',
        ),
        migrations.AddField(
            model_name='grade',
            name='concepts',
            field=models.ManyToManyField(blank=True, through='catalog.ConceptInGrade', to='catalog.Concept'),
        ),
    ]
